name: Python CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Using Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run unit tests
        run: 'python3 math_utils.test.py'